### ISSUE TITLE
Twig formatting

### ISSUE THREAD

**Issue by ajiho** [moetelo/twiggy#4]
First of all, thank you for this plugin，Because I spend most of my time writing HTML code, I think losing HTML intellisense would be very painful for me，And I habitually format the code (shift+alt+f), and vscode will prompt me that there is no formatting program，I don't want to go back to PHP Storm, so if there is a better development experience, I would like to get some advice from you

**Comment by moetelo** [comment]
https://github.com/VincentLanglet/Twig-CS-Fixer
This could work.

Don't want to integrate prettydiff here like the [vscode-twig-language-2 does](https://github.com/mblode/vscode-twig-language-2/blob/f62292b533e7c3628c3039214edf45869f8d16c9/src/extension.js#L19) because prettydiff itself is not well maintained ([no code changes since 2019, only the readme.md updates](https://github.com/prettydiff/prettydiff/commits/master/)).

**Comment by moetelo** [comment]
I see that [VincentLanglet/Twig-CS-Fixer](https://github.com/VincentLanglet/Twig-CS-Fixer) fixes only Twig-related issues. We need something above it to also format HTML.

**Comment by vralle** [comment]
Hi there!
How about build-in HTML formatter? VS Code has perfect support for HTML, HTML language server and Handlebars support.
settings.json
```
{
    "html.format.indentHandlebars": true,
    "html.format.templating": true,
}
```

**Comment by moetelo** [comment]
This could work: https://github.com/zackad/prettier-plugin-twig-melody

**Comment by moetelo** [comment]
Note that it uses https://github.com/VincentLanglet/Twig-CS-Fixer only if it is installed in the project. Twig-CS-Fixer formats only Twig code (`{{ }}`, `{% %}`).

I'll release it after I fix a bug with `"editor.formatOnSave": true`
