### ISSUE TITLE
Publish language server to npm

### ISSUE THREAD

**Issue by huesersohn** [moetelo/twiggy#5]
Could you publish the language server to npm? I'd like to be able to install it independently. Thanks in advance!

**Comment by moetelo** [comment]
Started using neovim lately, also missing the features I've developed for myself haha. Definitely will investigate into that!

Would be enough for neovim to work fine with Twig just using the language server provided by this repo?

The only vscode-specific feature is this thing:
https://github.com/moetelo/twiggy/blob/master/packages/vscode/src/autoInsert.ts
which inserts spaces into the brackets:  {{ | }} and {% | %}.

This is not included into the language server because I didn't figure out how to (if it's even possible).

**Comment by huesersohn** [comment]
Yes, I am currently using your language server inside neovim. I'd like to add it to Mason for ease of installing, see mason-org/mason-registry#3855

I first implemented a way downloading the VS Code extension from the store, but that way is not acutally allowed as per the ToS. So if the package itself was available on npm that would be great!

**Comment by moetelo** [comment]
@huesersohn 

https://github.com/moetelo/twiggy/commit/e085d4b1335dfc3cb5794fa7e8b18dcc9fcca80b
I have prepared everything for npm, although while testing I've restricted myself from republishing my own package:

```bash
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/twiggy-language-server - twiggy-language-server cannot be republished until 24 hours have passed.
```

Let's wait then. For now, for your https://github.com/mason-org/mason-registry/pull/3855, you can safely assume that the package will be installable via the `npm install twiggy-language-server` command (note `twiggy` instead of `twig`).

**Comment by Numkil** [comment]
Thanks!

**Comment by moetelo** [comment]
Does the naming inconsistency (i.e. twiggy-language-server instead of twig-language-server) affect any of your previous work, for example, in these PRs?

https://github.com/mason-org/mason-registry/pull/3855
https://github.com/neovim/nvim-lspconfig/pull/2939
https://github.com/williamboman/mason-lspconfig.nvim/pull/344

Would it be possible to use `twiggy-language-server` (with exactly this naming) in mason?

@huesersohn @Numkil

**Comment by Numkil** [comment]
Sure thing. I'll update my PR soon.

**Comment by moetelo** [comment]
https://www.npmjs.com/package/twiggy-language-server

@huesersohn @Numkil

**Comment by huesersohn** [comment]
Sadly this won't work with Mason because of the `"tree-sitter-twig": "workspace:*"` dependency. Can this be changed somehow?

**Comment by moetelo** [comment]
@huesersohn fixed, see 0.6.4

**Comment by huesersohn** [comment]
@moetelo Sorry to bother you again, but the package on npm does not contain the source code, just the package.json, LICENSE, and README.md files. Could you also include the dist folder in the package? That way one we don't have to build the package ourselves. Thanks!

**Comment by moetelo** [comment]
@huesersohn My bad. Will republish tomorrow

**Comment by moetelo** [comment]
@huesersohn Republished with `dist` folder included.

**Comment by moetelo** [comment]
@huesersohn Thank you too!
