### ISSUE TITLE
Include generated grammar files

### ISSUE THREAD

**Issue by jannisborgers** [moetelo/twiggy#60]
Thank you for the great work! This looks like the most complete Twig grammar and language server. I found your post in the official Twig discussion about an official language server.

I'm trying to port the language to the Zed editor by contributing to the zed-twig extension and wanted to use your grammar and possibly the language server as well.

In commit 510da88f3d221939321562dc4c4ebd4d53c67ef5 you put the generated grammar files into `.gitignore`. I haven't found any specific reasons for it, maybe package size?

Right now, Zed expects language extensions to include the grammar's `src/parser.c` file and tries to compile the grammar this way. Without it, the Zed extension cannot be installed, at least not without manually building the grammar first. While I would prefer to be able to `npm install` and `npm run build` within the Zed extension code, this does not seem to be possible at the moment.

I looked through a lot of tree sitter grammars and most of them include the generated files. Would you consider including them as well, to make using the grammar in other projects possible without having to build it first?

**Comment by moetelo** [comment]
Hi!

I’m excited to hear you’re looking to port the language to the Zed editor.

I chose to exclude `parser.c` because of its size and because of the reason that it could be easily generated from `grammar.js`.

As I understand it, the grammar in Zed is primarily used for highlighting purposes. In contrast, the language server in this repository uses Tree-sitter internally to analyze the AST and provide insights about the codebase. However, I’m considering migrating away from Tree-sitter to a custom lexer and parser (possibly even Twig's parser written in PHP) since relying on Tree-sitter in the language server may not be ideal.
 
Given this, I feel that using the exact same Tree-sitter grammar as in the language server might not provide much benefit. I recommend using any other grammar that you find suitable for highlighting the code, and using `twiggy-language-server` as a language server. This is what Neovim does: it [uses twiggy](https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#twiggy_language_server) for language server functionality and [gbprod/tree-sitter-twig](https://github.com/nvim-treesitter/nvim-treesitter/blob/c50981479e4271ec87c5a15ec991472bdec4f1b8/README.md?plain=1#L448) for syntax highlighting.

> this does not seem to be possible at the moment

Is there an issue at the Zed editor repo about this?

**Comment by jannisborgers** [comment]
Thank you very much for the quick response! I followed your advice and replaced only the language-server with twiggy-language-server and kept the `gbprod/tree-sitter-twig` grammar for syntax highlighting, which was already used by the original extension. So far, it works very nice. I get some errors because the server expects the framework configuration, but code completion and snippets work, which is super helpful!

My goal regarding Twig is actually a formatter. I’m very grateful that [zackad/prettier-plugin-twig](https://github.com/zackad/prettier-plugin-twig) exists, but in my contribution attempts I found that working with it’s lexer/parser was very complicated.

Then I found [tweag/topiary](https://github.com/tweag/topiary), which would not need an additional parser and works with tree sitter queries and capture instructions instead. With a well-built tree-sitter grammar for Twig, this could be a good way to format Twig code. Maybe that requires a different grammar, though?

**Comment by moetelo** [comment]
Yes, that would require a grammar that also includes HTML grammar in it. Twiggy grammar supports only twig syntax (`{{ ... }}`, `{% ... %}`)

**Comment by jannisborgers** [comment]
Have you worked in that direction? 

I assumed that could be handled by tree sitter injections, where the Twig grammar contains `content` nodes can be marked as being another language, and then tree-sitter can switch between parsing as HTML or Twig. More complex injection scenarios are very common in template languages like Twig, of course:

```twig
{% block content %}
<div {% for key, value in attributes %}{{ key }}={{ value }}{% endfor %}></div>

{# Or even… #}
<{{ element }}>Some content</{{ element }}>
{% endblock %}
```

Not the prettiest Twig, but valid.

Injections seem to be [unsupported by Topiary](https://github.com/tweag/topiary/issues/579), it seems… Maybe their [custom scopes](https://github.com/tweag/topiary/issues/579) could be helpful. Not sure if it’s worth to experiment with that.

Thanks for taking the time!
